//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Банк_Тест
{
    using System;
    using System.Collections.Generic;
    
    public partial class Приход
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Приход()
        {
            this.Детализация_прихода = new HashSet<Детализация_прихода>();
        }
    
        public int Id_Postuplenie { get; set; }
        public System.DateTime Дата_поступления { get; set; }
        public string Наименование_склада { get; set; }
        public string Наименование_организации { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Детализация_прихода> Детализация_прихода { get; set; }
        public virtual Организации Организации { get; set; }
        public virtual Склад Склад { get; set; }
    }
}
