//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Банк_Тест
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расход
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Расход()
        {
            this.Детализация_расхода = new HashSet<Детализация_расхода>();
        }
    
        public int Id_rashod { get; set; }
        public System.DateTime Дата_расхода { get; set; }
        public string Наименование_склада { get; set; }
        public string Наименование_организации { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Детализация_расхода> Детализация_расхода { get; set; }
        public virtual Организации Организации { get; set; }
        public virtual Склад Склад { get; set; }
    }
}
